spring:
  datasource:
    username: postgres
    password: postgres301946
    url: jdbc:postgresql://localhost:5432/new_internet_banking

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
